dist: trusty
sudo: false
language: node_js
node_js:
    - 8
cache:
  directories:
  - node_modules
before_install:
    - npm update
install:
    - npm install
script:
    - npm test
    - sonar-scanner -X
addons:
    sonarcloud:
        organization: "tomkoufakis" # the key of the org you chose at step #3
        